package com.example.myapplication;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageView;
import android.widget.PopupMenu;
import android.widget.SearchView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;
import java.util.List;

public class Inventory extends AppCompatActivity implements ShoeAdapter.ShoeClickListener{

    SearchView searchView;
    RecyclerView recyclerView;
    ShoeAdapter shoeAdapter;
    List<ShoeModel> shoeModelList = new ArrayList<>();

    ImageView backBtn, menupopbtn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_inventory);

        searchView = findViewById(R.id.searchView);
        recyclerView = findViewById(R.id.recyclerView);

        backBtn = findViewById(R.id.backBtn);
        backBtn.setOnClickListener(view -> startActivity(new Intent(getApplicationContext(), MainActivity.class)));

        menupopbtn = findViewById(R.id.menupopbtn);
        menupopbtn.setOnClickListener(view -> {
            PopupMenu popupMenu = new PopupMenu(getApplicationContext(), menupopbtn);
            popupMenu.getMenuInflater().inflate(R.menu.option_menu, popupMenu.getMenu());

            popupMenu.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener() {
                @Override
                public boolean onMenuItemClick(MenuItem menuItem) {
                    switch (menuItem.getItemId()) {

                        case R.id.resetUserPassword:
                            startActivity(new Intent(getApplicationContext(), Resetpassword.class));
                            return true;

                        case R.id.logoutbtn:
                            FirebaseAuth.getInstance().signOut();
                            startActivity(new Intent(getApplicationContext(), LoginActivity.class));
                            finish();
                            return true;
                    }
                    return false;
                }
            });
            popupMenu.show();
        });

        displaySearch();
        setData();
        displayRV();

    }

    // filtered list for searchView
    private void displaySearch() {
        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                List<ShoeModel> filteredList = new ArrayList<>();
                for (ShoeModel item: shoeModelList){
                    if (item.getName().toLowerCase().contains(newText.toLowerCase())){
                        filteredList.add(item);
                    }
                    shoeAdapter.filterList(filteredList);
                }
                return true;
            }
        });
    }

    // data for shoe names
    public void setData() {

        shoeModelList.add(new ShoeModel("Ada Biscotti"));
        shoeModelList.add(new ShoeModel("Ada Black"));
        shoeModelList.add(new ShoeModel("Ada Bleu"));
        shoeModelList.add(new ShoeModel("Ada Blush"));
        shoeModelList.add(new ShoeModel("Ada Daffodil"));
        shoeModelList.add(new ShoeModel("Ada Fleur"));
        shoeModelList.add(new ShoeModel("Ada Golden"));
        shoeModelList.add(new ShoeModel("Ada Periwinkle"));
        shoeModelList.add(new ShoeModel("Ada White"));
        shoeModelList.add(new ShoeModel("Adria LeBlanc"));
        shoeModelList.add(new ShoeModel("Adria Naturale"));
        shoeModelList.add(new ShoeModel("Adria Toscana"));
        shoeModelList.add(new ShoeModel("Akalia Palomino"));
        shoeModelList.add(new ShoeModel("Akalia White"));
        shoeModelList.add(new ShoeModel("Alaia Biscotti"));
        shoeModelList.add(new ShoeModel("Alaia Creme"));
        shoeModelList.add(new ShoeModel("Alaia Fleur"));
        shoeModelList.add(new ShoeModel("Alaia Toscana"));
        shoeModelList.add(new ShoeModel("Alana Black"));
        shoeModelList.add(new ShoeModel("Alana Bleu"));
        shoeModelList.add(new ShoeModel("Alana Fleur"));
        shoeModelList.add(new ShoeModel("Alana Palomino"));
        shoeModelList.add(new ShoeModel("Alana White"));
        shoeModelList.add(new ShoeModel("Alcott Biscotti"));
        shoeModelList.add(new ShoeModel("Alcott Palomino"));
        shoeModelList.add(new ShoeModel("Alcott Toscana"));
        shoeModelList.add(new ShoeModel("Alcott White"));
        shoeModelList.add(new ShoeModel("Alva Creme"));
        shoeModelList.add(new ShoeModel("Alva Naturale"));
        shoeModelList.add(new ShoeModel("Alva Noir"));
        shoeModelList.add(new ShoeModel("Amara Biscotti"));
        shoeModelList.add(new ShoeModel("Amara Fleur"));
        shoeModelList.add(new ShoeModel("Amara Orchid"));
        shoeModelList.add(new ShoeModel("Amara White"));
        shoeModelList.add(new ShoeModel("Amber Black"));
        shoeModelList.add(new ShoeModel("Amber Cashew"));
        shoeModelList.add(new ShoeModel("Amber Daffodil"));
        shoeModelList.add(new ShoeModel("Amber Lilac"));
        shoeModelList.add(new ShoeModel("Amber Oat"));
        shoeModelList.add(new ShoeModel("Amber White"));
        shoeModelList.add(new ShoeModel("Analia Palomino"));
        shoeModelList.add(new ShoeModel("Analia Toscana"));
        shoeModelList.add(new ShoeModel("Ashanti Biscotti"));
        shoeModelList.add(new ShoeModel("Ashanti Fleur"));
        shoeModelList.add(new ShoeModel("Ashanti White"));
        shoeModelList.add(new ShoeModel("Aztrid Black"));
        shoeModelList.add(new ShoeModel("Aztrid Cloud"));
        shoeModelList.add(new ShoeModel("Aztrid Nude"));
        shoeModelList.add(new ShoeModel("Bahari Biscotti"));
        shoeModelList.add(new ShoeModel("Bahari Ecru"));
        shoeModelList.add(new ShoeModel("Bahari Toscana"));
        shoeModelList.add(new ShoeModel("Becca Biscotti"));
        shoeModelList.add(new ShoeModel("Becca Fleur"));
        shoeModelList.add(new ShoeModel("Becca White"));
        shoeModelList.add(new ShoeModel("Beyza Biscotti"));
        shoeModelList.add(new ShoeModel("Beyza Cashew"));
        shoeModelList.add(new ShoeModel("Beyza Lime"));
        shoeModelList.add(new ShoeModel("Beyza Old Rose"));
        shoeModelList.add(new ShoeModel("Beyza Sierra"));
        shoeModelList.add(new ShoeModel("Beyza Tangerine1"));
        shoeModelList.add(new ShoeModel("Beyza Tricolor"));
        shoeModelList.add(new ShoeModel("Beyza White"));
        shoeModelList.add(new ShoeModel("Binx Biscotti"));
        shoeModelList.add(new ShoeModel("Binx LeBlanc"));
        shoeModelList.add(new ShoeModel("Binx Toscana"));
        shoeModelList.add(new ShoeModel("Blair Biscotti"));
        shoeModelList.add(new ShoeModel("Blair Palomino"));
        shoeModelList.add(new ShoeModel("Blair White"));
        shoeModelList.add(new ShoeModel("Blanche Black"));
        shoeModelList.add(new ShoeModel("Blanche Cashew"));
        shoeModelList.add(new ShoeModel("Blanche Cloud"));
        shoeModelList.add(new ShoeModel("Blanche Honey"));
        shoeModelList.add(new ShoeModel("Blanche Rosette"));
        shoeModelList.add(new ShoeModel("Blanche Tofu"));
        shoeModelList.add(new ShoeModel("Blanche Tortoise"));
        shoeModelList.add(new ShoeModel("Blanche Turtledove"));
        shoeModelList.add(new ShoeModel("Blythe Biscotti"));
        shoeModelList.add(new ShoeModel("Blythe Black"));
        shoeModelList.add(new ShoeModel("Blythe Cashew"));
        shoeModelList.add(new ShoeModel("Blythe White"));
        shoeModelList.add(new ShoeModel("Brea Toscana"));
        shoeModelList.add(new ShoeModel("Brea White"));
        shoeModelList.add(new ShoeModel("Brita Fleur"));
        shoeModelList.add(new ShoeModel("Brita Toscana"));
        shoeModelList.add(new ShoeModel("Brita White"));
        shoeModelList.add(new ShoeModel("Briza Creme"));
        shoeModelList.add(new ShoeModel("Briza Naturale"));
        shoeModelList.add(new ShoeModel("Briza Sedona"));
        shoeModelList.add(new ShoeModel("Calais LeBlanc"));
        shoeModelList.add(new ShoeModel("Calais Naturale"));
        shoeModelList.add(new ShoeModel("Cali Biscotti"));
        shoeModelList.add(new ShoeModel("Cali Creme"));
        shoeModelList.add(new ShoeModel("Cali Fleur"));
        shoeModelList.add(new ShoeModel("Cali Noir"));
        shoeModelList.add(new ShoeModel("Calista Black"));
        shoeModelList.add(new ShoeModel("Calista Fleur"));
        shoeModelList.add(new ShoeModel("Calista Toscana"));
        shoeModelList.add(new ShoeModel("Calista White"));
        shoeModelList.add(new ShoeModel("Calla Biscotti"));
        shoeModelList.add(new ShoeModel("Calla White"));
        shoeModelList.add(new ShoeModel("Candice Fleur"));
        shoeModelList.add(new ShoeModel("Candice Palomino"));
        shoeModelList.add(new ShoeModel("Candice Toscana"));
        shoeModelList.add(new ShoeModel("Caprice LeBlanc"));
        shoeModelList.add(new ShoeModel("Caprice Noir"));
        shoeModelList.add(new ShoeModel("Caprice Toast"));
        shoeModelList.add(new ShoeModel("Cari Beige"));
        shoeModelList.add(new ShoeModel("Cari Biscotti"));
        shoeModelList.add(new ShoeModel("Cari BlackLeather"));
        shoeModelList.add(new ShoeModel("Cari BlackSuede"));
        shoeModelList.add(new ShoeModel("Cari BlancGray"));
        shoeModelList.add(new ShoeModel("Cari Cashew"));
        shoeModelList.add(new ShoeModel("Cari Mauve"));
        shoeModelList.add(new ShoeModel("Cari Milk"));
        shoeModelList.add(new ShoeModel("Cari NudeLeather"));
        shoeModelList.add(new ShoeModel("Cari NudeSuede"));
        shoeModelList.add(new ShoeModel("Cari Tan"));
        shoeModelList.add(new ShoeModel("Cari Toffee"));
        shoeModelList.add(new ShoeModel("Cari WineRed"));
        shoeModelList.add(new ShoeModel("Carin Creme"));
        shoeModelList.add(new ShoeModel("Carin LeBlanc"));
        shoeModelList.add(new ShoeModel("Carin Naturale"));
        shoeModelList.add(new ShoeModel("Carin NaturaleOld"));
        shoeModelList.add(new ShoeModel("Carin Sedona"));
        shoeModelList.add(new ShoeModel("Carin Toscana"));
        shoeModelList.add(new ShoeModel("Casia Bleu"));
        shoeModelList.add(new ShoeModel("Casia Fleur"));
        shoeModelList.add(new ShoeModel("Casia Palomino"));
        shoeModelList.add(new ShoeModel("Casia White"));
        shoeModelList.add(new ShoeModel("Caya Black"));
        shoeModelList.add(new ShoeModel("Caya Bone"));
        shoeModelList.add(new ShoeModel("Caya Tortoise"));
        shoeModelList.add(new ShoeModel("Caya White"));
        shoeModelList.add(new ShoeModel("Celeste Black"));
        shoeModelList.add(new ShoeModel("Celeste Cloud"));
        shoeModelList.add(new ShoeModel("Celeste Palomino"));
        shoeModelList.add(new ShoeModel("Chantal White"));
        shoeModelList.add(new ShoeModel("Charlotte Black"));
        shoeModelList.add(new ShoeModel("Charlotte Nude"));
        shoeModelList.add(new ShoeModel("Charlotte NudeLeather"));
        shoeModelList.add(new ShoeModel("Charlotte White"));
        shoeModelList.add(new ShoeModel("Ciera LeBlanc"));
        shoeModelList.add(new ShoeModel("Cinzia Fleur"));
        shoeModelList.add(new ShoeModel("Cinzia LeBlanc"));
        shoeModelList.add(new ShoeModel("Cinzia Palomino"));
        shoeModelList.add(new ShoeModel("Cinzia Toscana"));
        shoeModelList.add(new ShoeModel("Cirila Creme"));
        shoeModelList.add(new ShoeModel("Cirila Naturale"));
        shoeModelList.add(new ShoeModel("Citla Claro"));
        shoeModelList.add(new ShoeModel("Citla LeBlanc"));
        shoeModelList.add(new ShoeModel("Citla Naturale"));
        shoeModelList.add(new ShoeModel("Citla Sedona"));
        shoeModelList.add(new ShoeModel("Clea Naturale"));
        shoeModelList.add(new ShoeModel("Clea Noir"));
        shoeModelList.add(new ShoeModel("Cleo Biscotti"));
        shoeModelList.add(new ShoeModel("Cleo Black"));
        shoeModelList.add(new ShoeModel("Cleo Naturale"));
        shoeModelList.add(new ShoeModel("Cleo Toscana"));
        shoeModelList.add(new ShoeModel("Cora BlackSuede"));
        shoeModelList.add(new ShoeModel("Cora NudeSuede"));
        shoeModelList.add(new ShoeModel("Cora TanSuede"));
        shoeModelList.add(new ShoeModel("Corin Black"));
        shoeModelList.add(new ShoeModel("Corin BlancGray"));
        shoeModelList.add(new ShoeModel("Corin Mauve"));
        shoeModelList.add(new ShoeModel("Corin Nude"));
        shoeModelList.add(new ShoeModel("Corin OldRose"));
        shoeModelList.add(new ShoeModel("Corin Tan"));
        shoeModelList.add(new ShoeModel("Corin White"));
        shoeModelList.add(new ShoeModel("Dakari Biscotti"));
        shoeModelList.add(new ShoeModel("Dakari LeBlanc"));
        shoeModelList.add(new ShoeModel("Dakari Naturale"));
        shoeModelList.add(new ShoeModel("Dakari Toscana"));
        shoeModelList.add(new ShoeModel("Damari Biscotti"));
        shoeModelList.add(new ShoeModel("Damari Palomino"));
        shoeModelList.add(new ShoeModel("Damari Toscana"));
        shoeModelList.add(new ShoeModel("Damia LeBlanc"));
        shoeModelList.add(new ShoeModel("Damia Noir"));
        shoeModelList.add(new ShoeModel("Damia Toscana"));
        shoeModelList.add(new ShoeModel("Dania Ochre"));
        shoeModelList.add(new ShoeModel("Dania OldRose"));
        shoeModelList.add(new ShoeModel("Dania White"));
        shoeModelList.add(new ShoeModel("Darika Creme"));
        shoeModelList.add(new ShoeModel("Darika Fleur"));
        shoeModelList.add(new ShoeModel("Darika LeBlanc"));
        shoeModelList.add(new ShoeModel("Darika Naturale"));
        shoeModelList.add(new ShoeModel("Darinka Naturale"));
        shoeModelList.add(new ShoeModel("Darinka Noir"));
        shoeModelList.add(new ShoeModel("Darinka Toscana"));
        shoeModelList.add(new ShoeModel("Darya Citron"));
        shoeModelList.add(new ShoeModel("Darya Nude"));
        shoeModelList.add(new ShoeModel("Darya White"));
        shoeModelList.add(new ShoeModel("Davina Naturale"));
        shoeModelList.add(new ShoeModel("Davina Noir"));
        shoeModelList.add(new ShoeModel("Dawn Biscotti"));
        shoeModelList.add(new ShoeModel("Dawn Black"));
        shoeModelList.add(new ShoeModel("Dawn Cashew"));
        shoeModelList.add(new ShoeModel("Dawn Honey"));
        shoeModelList.add(new ShoeModel("Dawn Tortoise"));
        shoeModelList.add(new ShoeModel("Dawn White"));
        shoeModelList.add(new ShoeModel("Dayra Nude"));
        shoeModelList.add(new ShoeModel("Dayra Pecan"));
        shoeModelList.add(new ShoeModel("Dayra White"));
        shoeModelList.add(new ShoeModel("Dazia Fleur"));
        shoeModelList.add(new ShoeModel("Dazia Toast"));
        shoeModelList.add(new ShoeModel("Dazia White"));
        shoeModelList.add(new ShoeModel("Deja Fleur"));
        shoeModelList.add(new ShoeModel("Deja LeBlanc"));
        shoeModelList.add(new ShoeModel("Deja Sedona"));
        shoeModelList.add(new ShoeModel("Devi Bisque"));
        shoeModelList.add(new ShoeModel("Devi Creme"));
        shoeModelList.add(new ShoeModel("Devi Fleur"));
        shoeModelList.add(new ShoeModel("Devi LeBlanc"));
        shoeModelList.add(new ShoeModel("Devi Naturale"));
        shoeModelList.add(new ShoeModel("Devi Toscana"));
        shoeModelList.add(new ShoeModel("Dimitra LeBlanc"));
        shoeModelList.add(new ShoeModel("Dimitra Toscana"));
        shoeModelList.add(new ShoeModel("Divya Biscotti"));
        shoeModelList.add(new ShoeModel("Divya Black"));
        shoeModelList.add(new ShoeModel("Divya Fleur"));
        shoeModelList.add(new ShoeModel("Divya Toscana"));
        shoeModelList.add(new ShoeModel("Dorca Biscotti"));
        shoeModelList.add(new ShoeModel("Dorca LeBlanc"));
        shoeModelList.add(new ShoeModel("Dorca Toscana"));
        shoeModelList.add(new ShoeModel("Dreya LeBlanc"));
        shoeModelList.add(new ShoeModel("Dreya Naturale"));
        shoeModelList.add(new ShoeModel("Dreya Noir"));
        shoeModelList.add(new ShoeModel("Dreya Toscana"));
        shoeModelList.add(new ShoeModel("Dyani Chamois"));
        shoeModelList.add(new ShoeModel("Dyani LeBlanc"));
        shoeModelList.add(new ShoeModel("Dyani Noir"));
        shoeModelList.add(new ShoeModel("Eara Naturale"));
        shoeModelList.add(new ShoeModel("Eara Noir"));
        shoeModelList.add(new ShoeModel("Efia LeBlanc"));
        shoeModelList.add(new ShoeModel("Efia Naturale"));
        shoeModelList.add(new ShoeModel("Efia Noir"));
        shoeModelList.add(new ShoeModel("Efia Toscana"));
        shoeModelList.add(new ShoeModel("Eira Biscotti"));
        shoeModelList.add(new ShoeModel("Eira Fleur"));
        shoeModelList.add(new ShoeModel("Eira LeBlanc"));
        shoeModelList.add(new ShoeModel("Eira Palomino"));
        shoeModelList.add(new ShoeModel("Elakshi Sandstone"));
        shoeModelList.add(new ShoeModel("Elakshi Sierra"));
        shoeModelList.add(new ShoeModel("Elakshi White"));
        shoeModelList.add(new ShoeModel("Elayna Amber"));
        shoeModelList.add(new ShoeModel("Elayna Aqua"));
        shoeModelList.add(new ShoeModel("Elayna Citron"));
        shoeModelList.add(new ShoeModel("Elayna White"));
        shoeModelList.add(new ShoeModel("Eliri Biscotti"));
        shoeModelList.add(new ShoeModel("Eliri Cashew"));
        shoeModelList.add(new ShoeModel("Eliri Ecru"));
        shoeModelList.add(new ShoeModel("Eliri White"));
        shoeModelList.add(new ShoeModel("Elva LeBlanc"));
        shoeModelList.add(new ShoeModel("Elva Palomino"));
        shoeModelList.add(new ShoeModel("Elva Toscana"));
        shoeModelList.add(new ShoeModel("Emari Creme"));
        shoeModelList.add(new ShoeModel("Emari Fleur"));
        shoeModelList.add(new ShoeModel("Emari Palomino"));
        shoeModelList.add(new ShoeModel("Emeli Biscotti"));
        shoeModelList.add(new ShoeModel("Emeli Creme"));
        shoeModelList.add(new ShoeModel("Emeli Toscana"));
        shoeModelList.add(new ShoeModel("Enari Naturale"));
        shoeModelList.add(new ShoeModel("Enari Noir"));
        shoeModelList.add(new ShoeModel("Enari Rojo"));
        shoeModelList.add(new ShoeModel("Ercila Bleu"));
        shoeModelList.add(new ShoeModel("Ercila Fleur"));
        shoeModelList.add(new ShoeModel("Ercila LeBlanc"));
        shoeModelList.add(new ShoeModel("Erma Fleur"));
        shoeModelList.add(new ShoeModel("Erma Palomino"));
        shoeModelList.add(new ShoeModel("Erma White"));
        shoeModelList.add(new ShoeModel("Eshika Calico"));
        shoeModelList.add(new ShoeModel("Eshika Fleur"));
        shoeModelList.add(new ShoeModel("Eshika LeBlanc"));
        shoeModelList.add(new ShoeModel("Eula Biscotti"));
        shoeModelList.add(new ShoeModel("Eula Noir"));
        shoeModelList.add(new ShoeModel("Eula Palomino"));
        shoeModelList.add(new ShoeModel("Ezra Black"));
        shoeModelList.add(new ShoeModel("Ezra Fleur"));
        shoeModelList.add(new ShoeModel("Ezra Nude"));
        shoeModelList.add(new ShoeModel("Ezra Palomino"));
        shoeModelList.add(new ShoeModel("Ezra White"));
        shoeModelList.add(new ShoeModel("Faiqa Fleur"));
        shoeModelList.add(new ShoeModel("Faiqa LeBlanc"));
        shoeModelList.add(new ShoeModel("Faiqa Majolica"));
        shoeModelList.add(new ShoeModel("Faiqa Mist"));
        shoeModelList.add(new ShoeModel("Faiza Biscotti"));
        shoeModelList.add(new ShoeModel("Faiza Cappuccino"));
        shoeModelList.add(new ShoeModel("Faiza White"));
        shoeModelList.add(new ShoeModel("Farida LeBlanc"));
        shoeModelList.add(new ShoeModel("Farida Naturale"));
        shoeModelList.add(new ShoeModel("Fatou Creme"));
        shoeModelList.add(new ShoeModel("Fatou Naturale"));
        shoeModelList.add(new ShoeModel("Fatou Noir"));
        shoeModelList.add(new ShoeModel("Fatou Sedona"));
        shoeModelList.add(new ShoeModel("Fiza LeBlanc"));
        shoeModelList.add(new ShoeModel("Fiza Naturale"));
        shoeModelList.add(new ShoeModel("Florentine Bisque"));
        shoeModelList.add(new ShoeModel("Florentine LeBlanc"));
        shoeModelList.add(new ShoeModel("Fraya Creme"));
        shoeModelList.add(new ShoeModel("Fraya LeBlanc1"));
        shoeModelList.add(new ShoeModel("Fraya Naturale1"));
        shoeModelList.add(new ShoeModel("Freda Black"));
        shoeModelList.add(new ShoeModel("Freda Bleu"));
        shoeModelList.add(new ShoeModel("Freda Daffodil"));
        shoeModelList.add(new ShoeModel("Freda White"));
        shoeModelList.add(new ShoeModel("Fritz Bleu"));
        shoeModelList.add(new ShoeModel("Fritz Noir"));
        shoeModelList.add(new ShoeModel("Fritz Toscana"));
        shoeModelList.add(new ShoeModel("Gada LeBlanc"));
        shoeModelList.add(new ShoeModel("Gada Naturale"));
        shoeModelList.add(new ShoeModel("Gada Noir"));
        shoeModelList.add(new ShoeModel("Gajra Biscotti"));
        shoeModelList.add(new ShoeModel("Gajra Fleur"));
        shoeModelList.add(new ShoeModel("Gajra LeBlanc"));
        shoeModelList.add(new ShoeModel("Galea Biscotti"));
        shoeModelList.add(new ShoeModel("Galea Toscana"));
        shoeModelList.add(new ShoeModel("Galea White"));
        shoeModelList.add(new ShoeModel("Gali LeBlanc"));
        shoeModelList.add(new ShoeModel("Gali Naturale"));
        shoeModelList.add(new ShoeModel("Gali Oceane"));
        shoeModelList.add(new ShoeModel("Galia BlueMist"));
        shoeModelList.add(new ShoeModel("Galia Periwinkle"));
        shoeModelList.add(new ShoeModel("Galia White"));
        shoeModelList.add(new ShoeModel("Gauri Biscotti"));
        shoeModelList.add(new ShoeModel("Gauri Black"));
        shoeModelList.add(new ShoeModel("Gauri Caramel"));
        shoeModelList.add(new ShoeModel("Gauri Lilac"));
        shoeModelList.add(new ShoeModel("Gauri Rosewater"));
        shoeModelList.add(new ShoeModel("Gauri Tangerine"));
        shoeModelList.add(new ShoeModel("Gauri White"));
        shoeModelList.add(new ShoeModel("Gauri WineRed"));
        shoeModelList.add(new ShoeModel("Gayatri LeBlanc"));
        shoeModelList.add(new ShoeModel("Gayatri Naturale"));
        shoeModelList.add(new ShoeModel("Gayatri Toscana"));
        shoeModelList.add(new ShoeModel("Georgina Nude"));
        shoeModelList.add(new ShoeModel("Gerta Mist"));
        shoeModelList.add(new ShoeModel("Gerta Naturale"));
        shoeModelList.add(new ShoeModel("Gerta Toscana"));
        shoeModelList.add(new ShoeModel("Gerta White"));
        shoeModelList.add(new ShoeModel("Giada Black"));
        shoeModelList.add(new ShoeModel("Giada Rosette"));
        shoeModelList.add(new ShoeModel("Giada Toast"));
        shoeModelList.add(new ShoeModel("Giada White"));
        shoeModelList.add(new ShoeModel("Giavanna Creme"));
        shoeModelList.add(new ShoeModel("Giavanna Noir"));
        shoeModelList.add(new ShoeModel("Giavanna Toscana"));
        shoeModelList.add(new ShoeModel("Gita Biscotti"));
        shoeModelList.add(new ShoeModel("Gita Black"));
        shoeModelList.add(new ShoeModel("Gita Natuarale"));
        shoeModelList.add(new ShoeModel("Gita Toscana"));
        shoeModelList.add(new ShoeModel("Hada Biscotti"));
        shoeModelList.add(new ShoeModel("Hada Cashew"));
        shoeModelList.add(new ShoeModel("Hada Mauve"));
        shoeModelList.add(new ShoeModel("Hada Nude"));
        shoeModelList.add(new ShoeModel("Hada White"));
        shoeModelList.add(new ShoeModel("Hadiya Aqua"));
        shoeModelList.add(new ShoeModel("Hadiya Cashew"));
        shoeModelList.add(new ShoeModel("Hadiya Orchid"));
        shoeModelList.add(new ShoeModel("Hadiya White"));
        shoeModelList.add(new ShoeModel("Hailey Black"));
        shoeModelList.add(new ShoeModel("Hailey Caramel"));
        shoeModelList.add(new ShoeModel("Hailey Nude"));
        shoeModelList.add(new ShoeModel("Hailey White"));
        shoeModelList.add(new ShoeModel("Haira LeBlanc"));
        shoeModelList.add(new ShoeModel("Haira Naturale"));
        shoeModelList.add(new ShoeModel("Hajra Biscotti"));
        shoeModelList.add(new ShoeModel("Hajra Creme"));
        shoeModelList.add(new ShoeModel("Hajra LeBlanc"));
        shoeModelList.add(new ShoeModel("Hajra Naturale"));
        shoeModelList.add(new ShoeModel("Hajra Revera"));
        shoeModelList.add(new ShoeModel("Hajra Toscana"));
        shoeModelList.add(new ShoeModel("Haldis Canta"));
        shoeModelList.add(new ShoeModel("Haldis Dyad"));
        shoeModelList.add(new ShoeModel("Haldis LeBlanc"));
        shoeModelList.add(new ShoeModel("Haldis Naturale"));
        shoeModelList.add(new ShoeModel("Haldis Noir"));
        shoeModelList.add(new ShoeModel("Haldis Palmera"));
        shoeModelList.add(new ShoeModel("Haldis Rayo"));
        shoeModelList.add(new ShoeModel("Haldis Rosa"));
        shoeModelList.add(new ShoeModel("Haldis Sedona"));
        shoeModelList.add(new ShoeModel("Halia Celadon"));
        shoeModelList.add(new ShoeModel("Halia Fleur"));
        shoeModelList.add(new ShoeModel("Halia LeBlanc"));
        shoeModelList.add(new ShoeModel("Hania Biscotti"));
        shoeModelList.add(new ShoeModel("Hania Nude"));
        shoeModelList.add(new ShoeModel("Hania White"));
        shoeModelList.add(new ShoeModel("Haniya LeBlanc"));
        shoeModelList.add(new ShoeModel("Haniya Naturale"));
        shoeModelList.add(new ShoeModel("Haniya Woven"));
        shoeModelList.add(new ShoeModel("Hanvika Biscotti"));
        shoeModelList.add(new ShoeModel("Hanvika LeBlanc"));
        shoeModelList.add(new ShoeModel("Hara Biscotti"));
        shoeModelList.add(new ShoeModel("Hara LeBlanc"));
        shoeModelList.add(new ShoeModel("Hara Naturale"));
        shoeModelList.add(new ShoeModel("Harini LeBlanc"));
        shoeModelList.add(new ShoeModel("Harini Naturale"));
        shoeModelList.add(new ShoeModel("Harini Noir"));
        shoeModelList.add(new ShoeModel("Harri LeBlanc"));
        shoeModelList.add(new ShoeModel("Harri Noir"));
        shoeModelList.add(new ShoeModel("Havika LeBlanc"));
        shoeModelList.add(new ShoeModel("Havika Noir"));
        shoeModelList.add(new ShoeModel("Havika Toscana"));
        shoeModelList.add(new ShoeModel("Haya Biscotti"));
        shoeModelList.add(new ShoeModel("Haya Black"));
        shoeModelList.add(new ShoeModel("Haya Cashew"));
        shoeModelList.add(new ShoeModel("Haya Nude"));
        shoeModelList.add(new ShoeModel("Haya White"));
        shoeModelList.add(new ShoeModel("Henika Chamois"));
        shoeModelList.add(new ShoeModel("Henika Noir"));
        shoeModelList.add(new ShoeModel("Huda Biscotti"));
        shoeModelList.add(new ShoeModel("Huda Fleur"));
        shoeModelList.add(new ShoeModel("Huda White"));
        shoeModelList.add(new ShoeModel("Ida Biscotti"));
        shoeModelList.add(new ShoeModel("Ida Black"));
        shoeModelList.add(new ShoeModel("Ida White"));
        shoeModelList.add(new ShoeModel("Iman Biscotti"));
        shoeModelList.add(new ShoeModel("Iman LeBlanc"));
        shoeModelList.add(new ShoeModel("Iman Naturale"));
        shoeModelList.add(new ShoeModel("Inez Biscotti"));
        shoeModelList.add(new ShoeModel("Inez Creme"));
        shoeModelList.add(new ShoeModel("Inez Palomino"));
        shoeModelList.add(new ShoeModel("Ingrid White"));
        shoeModelList.add(new ShoeModel("Iqra Noir"));
        shoeModelList.add(new ShoeModel("Jaca Fleur"));
        shoeModelList.add(new ShoeModel("Jaca Fleur1"));
        shoeModelList.add(new ShoeModel("Jaca LeBlanc"));
        shoeModelList.add(new ShoeModel("Jaca LeBlanc1"));
        shoeModelList.add(new ShoeModel("Jaca Naturale"));
        shoeModelList.add(new ShoeModel("Jaca Naturale1"));
        shoeModelList.add(new ShoeModel("Jaca Sedona"));
        shoeModelList.add(new ShoeModel("Jaci Biscotti"));
        shoeModelList.add(new ShoeModel("Jada LeBlanc"));
        shoeModelList.add(new ShoeModel("Jada Naturale"));
        shoeModelList.add(new ShoeModel("Jada Noir"));
        shoeModelList.add(new ShoeModel("Jada Revera"));
        shoeModelList.add(new ShoeModel("Jada Rocio"));
        shoeModelList.add(new ShoeModel("Jaliya Black1"));
        shoeModelList.add(new ShoeModel("Jaliya Calke Green"));
        shoeModelList.add(new ShoeModel("Jaliya Nude"));
        shoeModelList.add(new ShoeModel("Jaliya White"));
        shoeModelList.add(new ShoeModel("Janeva Biscotti"));
        shoeModelList.add(new ShoeModel("Janeva LeBlanc"));
        shoeModelList.add(new ShoeModel("Janeva Naturale"));
        shoeModelList.add(new ShoeModel("Janeva Palomino"));
        shoeModelList.add(new ShoeModel("Jaria Chamois"));
        shoeModelList.add(new ShoeModel("Jaria Noir"));
        shoeModelList.add(new ShoeModel("Jemimah Black"));
        shoeModelList.add(new ShoeModel("Jemimah Gray"));
        shoeModelList.add(new ShoeModel("Jemimah Light Blue"));
        shoeModelList.add(new ShoeModel("Jemimah Nude"));
        shoeModelList.add(new ShoeModel("Jemimah White"));
        shoeModelList.add(new ShoeModel("Joia Brassica"));
        shoeModelList.add(new ShoeModel("Joia LeBlanc"));
        shoeModelList.add(new ShoeModel("Jovana BiscottiNoir"));
        shoeModelList.add(new ShoeModel("Jovana Fleur"));
        shoeModelList.add(new ShoeModel("Jovana LeBlanc"));
        shoeModelList.add(new ShoeModel("Jovana Naturale"));
        shoeModelList.add(new ShoeModel("Kadija Biscotti"));
        shoeModelList.add(new ShoeModel("Kadija Creme"));
        shoeModelList.add(new ShoeModel("Kadija Fleur"));
        shoeModelList.add(new ShoeModel("Kadija Noir"));
        shoeModelList.add(new ShoeModel("Kaia Biscotti"));
        shoeModelList.add(new ShoeModel("Kaia Fleur"));
        shoeModelList.add(new ShoeModel("Kaia Majolica"));
        shoeModelList.add(new ShoeModel("Kaia Mist"));
        shoeModelList.add(new ShoeModel("Kaia Palomino"));
        shoeModelList.add(new ShoeModel("Kaia Toscana"));
        shoeModelList.add(new ShoeModel("Kaia White"));
        shoeModelList.add(new ShoeModel("Kaija LeBlanc"));
        shoeModelList.add(new ShoeModel("Kaija Noir"));
        shoeModelList.add(new ShoeModel("Kaira Cashew"));
        shoeModelList.add(new ShoeModel("Kaira Toscana"));
        shoeModelList.add(new ShoeModel("Kaira White"));
        shoeModelList.add(new ShoeModel("Kala Biscotti"));
        shoeModelList.add(new ShoeModel("Kala Toscana"));
        shoeModelList.add(new ShoeModel("Kala White"));
        shoeModelList.add(new ShoeModel("Kalani Dimity"));
        shoeModelList.add(new ShoeModel("Kalani LeBlanc"));
        shoeModelList.add(new ShoeModel("Kalani Noir"));
        shoeModelList.add(new ShoeModel("Kali Cashew"));
        shoeModelList.add(new ShoeModel("Kali White"));
        shoeModelList.add(new ShoeModel("Kamala Biscotti"));
        shoeModelList.add(new ShoeModel("Kamala Fleur"));
        shoeModelList.add(new ShoeModel("Kamala LeBlanc"));
        shoeModelList.add(new ShoeModel("Kanika Biscotti"));
        shoeModelList.add(new ShoeModel("Kanika Noir"));
        shoeModelList.add(new ShoeModel("Kanika Palomino"));
        shoeModelList.add(new ShoeModel("Kaori Biscotti"));
        shoeModelList.add(new ShoeModel("Kaori Cashew"));
        shoeModelList.add(new ShoeModel("Kaori White"));
        shoeModelList.add(new ShoeModel("Kashvi Black"));
        shoeModelList.add(new ShoeModel("Kashvi Nude"));
        shoeModelList.add(new ShoeModel("Kashvi White"));
        shoeModelList.add(new ShoeModel("Kashvi Wine Red"));
        shoeModelList.add(new ShoeModel("Katara Fleur"));
        shoeModelList.add(new ShoeModel("Katara LeBlanc"));
        shoeModelList.add(new ShoeModel("Kerala Biscotti"));
        shoeModelList.add(new ShoeModel("Kerala LeBlanc"));
        shoeModelList.add(new ShoeModel("Kerala Naturale"));
        shoeModelList.add(new ShoeModel("Kerala Toscana"));
        shoeModelList.add(new ShoeModel("Keva LeBlanc"));
        shoeModelList.add(new ShoeModel("Keva Nude"));
        shoeModelList.add(new ShoeModel("Keva Sedona"));
        shoeModelList.add(new ShoeModel("Keva Toscana"));
        shoeModelList.add(new ShoeModel("Kiari Biscotti"));
        shoeModelList.add(new ShoeModel("Kiari Fleur"));
        shoeModelList.add(new ShoeModel("Kiari Toscana"));
        shoeModelList.add(new ShoeModel("Kimaya LeBlanc"));
        shoeModelList.add(new ShoeModel("Kimaya Naturale"));
        shoeModelList.add(new ShoeModel("Kimaya Noir"));
        shoeModelList.add(new ShoeModel("Kimika LeBlanc"));
        shoeModelList.add(new ShoeModel("Kimika Naturale"));
        shoeModelList.add(new ShoeModel("Kimika Noir"));
        shoeModelList.add(new ShoeModel("Kriva LeBlanc"));
        shoeModelList.add(new ShoeModel("Kriva Noir"));
        shoeModelList.add(new ShoeModel("Kriva Paradizo"));
        shoeModelList.add(new ShoeModel("Kriva Rojo"));
        shoeModelList.add(new ShoeModel("Kyla LeBlanc"));
        shoeModelList.add(new ShoeModel("Lacara LeBlanc"));
        shoeModelList.add(new ShoeModel("Lacara Naturale"));
        shoeModelList.add(new ShoeModel("Lacara Toscana"));
        shoeModelList.add(new ShoeModel("Latara Chamois"));
        shoeModelList.add(new ShoeModel("Latara LeBlanc"));
        shoeModelList.add(new ShoeModel("Latara Naturale"));
        shoeModelList.add(new ShoeModel("Layan Biscotti"));
        shoeModelList.add(new ShoeModel("Layan Fleur"));
        shoeModelList.add(new ShoeModel("Layan LeBlanc"));
        shoeModelList.add(new ShoeModel("Layla Biscotti"));
        shoeModelList.add(new ShoeModel("Layla Fleur"));
        shoeModelList.add(new ShoeModel("Layla White"));
        shoeModelList.add(new ShoeModel("Leana Dawn"));
        shoeModelList.add(new ShoeModel("Leana Palomino"));
        shoeModelList.add(new ShoeModel("Leana SageGreen"));
        shoeModelList.add(new ShoeModel("Leana Tortoise"));
        shoeModelList.add(new ShoeModel("Leana White"));
        shoeModelList.add(new ShoeModel("Litzy Bicotti"));
        shoeModelList.add(new ShoeModel("Litzy Bleu"));
        shoeModelList.add(new ShoeModel("Litzy LeBlanc"));
        shoeModelList.add(new ShoeModel("Litzy Noir"));
        shoeModelList.add(new ShoeModel("Litzy Toscana"));
        shoeModelList.add(new ShoeModel("Londyn BlancGray"));
        shoeModelList.add(new ShoeModel("Londyn White"));
        shoeModelList.add(new ShoeModel("Lora Black1"));
        shoeModelList.add(new ShoeModel("Lora Nude1"));
        shoeModelList.add(new ShoeModel("Lora White"));
        shoeModelList.add(new ShoeModel("Lorelei Biscotti"));
        shoeModelList.add(new ShoeModel("Lorelei Palomino"));
        shoeModelList.add(new ShoeModel("Lorelei Toscana"));
        shoeModelList.add(new ShoeModel("Loretta Beige"));
        shoeModelList.add(new ShoeModel("Loretta Black"));
        shoeModelList.add(new ShoeModel("Loretta Fleur"));
        shoeModelList.add(new ShoeModel("Loretta White"));
        shoeModelList.add(new ShoeModel("Lori Biscotti"));
        shoeModelList.add(new ShoeModel("Lori Fleur"));
        shoeModelList.add(new ShoeModel("Lori Palomino"));
        shoeModelList.add(new ShoeModel("Lori White"));
        shoeModelList.add(new ShoeModel("Luxi Biscotti"));
        shoeModelList.add(new ShoeModel("Luxi LeBlanc"));
        shoeModelList.add(new ShoeModel("Luxi Naturale"));
        shoeModelList.add(new ShoeModel("Luxi Noir"));
        shoeModelList.add(new ShoeModel("Macara Creme"));
        shoeModelList.add(new ShoeModel("Macara Fleur"));
        shoeModelList.add(new ShoeModel("Macara LeBlanc"));
        shoeModelList.add(new ShoeModel("Macara Naturale"));
        shoeModelList.add(new ShoeModel("Maija LeBlanc"));
        shoeModelList.add(new ShoeModel("Maija Naturale"));
        shoeModelList.add(new ShoeModel("Maija Revera"));
        shoeModelList.add(new ShoeModel("Malia Black"));
        shoeModelList.add(new ShoeModel("Malia Nude"));
        shoeModelList.add(new ShoeModel("Malia Tortoise"));
        shoeModelList.add(new ShoeModel("Malia White"));
        shoeModelList.add(new ShoeModel("Malka Fleur"));
        shoeModelList.add(new ShoeModel("Malka LeBlanc"));
        shoeModelList.add(new ShoeModel("Malka Naturale"));
        shoeModelList.add(new ShoeModel("Malka Rosa"));
        shoeModelList.add(new ShoeModel("Malka Sedona"));
        shoeModelList.add(new ShoeModel("Marica Biscotti"));
        shoeModelList.add(new ShoeModel("Marica Creme"));
        shoeModelList.add(new ShoeModel("Marica LeBlanc"));
        shoeModelList.add(new ShoeModel("Marica Noir"));
        shoeModelList.add(new ShoeModel("Marie Black"));
        shoeModelList.add(new ShoeModel("Marie Blush"));
        shoeModelList.add(new ShoeModel("Marie Nude"));
        shoeModelList.add(new ShoeModel("Marie Periwinkle"));
        shoeModelList.add(new ShoeModel("Marie Taupe"));
        shoeModelList.add(new ShoeModel("Marie White"));
        shoeModelList.add(new ShoeModel("Marie WineRed"));
        shoeModelList.add(new ShoeModel("Marzia Cashew"));
        shoeModelList.add(new ShoeModel("Marzia Claro"));
        shoeModelList.add(new ShoeModel("Marzia Ecru"));
        shoeModelList.add(new ShoeModel("Marzia White"));
        shoeModelList.add(new ShoeModel("Meera Biscotti"));
        shoeModelList.add(new ShoeModel("Meera Cashew"));
        shoeModelList.add(new ShoeModel("Meera White"));
        shoeModelList.add(new ShoeModel("Melina Toast"));
        shoeModelList.add(new ShoeModel("Melina Toscana"));
        shoeModelList.add(new ShoeModel("Melina White"));
        shoeModelList.add(new ShoeModel("Meya Black"));
        shoeModelList.add(new ShoeModel("Meya Cappuccino"));
        shoeModelList.add(new ShoeModel("Meya Fleur"));
        shoeModelList.add(new ShoeModel("Meya Nude"));
        shoeModelList.add(new ShoeModel("Meya White"));
        shoeModelList.add(new ShoeModel("Mireya Biscotti"));
        shoeModelList.add(new ShoeModel("Mireya Naturale"));
        shoeModelList.add(new ShoeModel("Mireya White"));
        shoeModelList.add(new ShoeModel("Mohini Nude"));
        shoeModelList.add(new ShoeModel("Mohini White"));
        shoeModelList.add(new ShoeModel("Moxi"));
        shoeModelList.add(new ShoeModel("Moxi Daffodil"));
        shoeModelList.add(new ShoeModel("Moxi Fleur"));
        shoeModelList.add(new ShoeModel("Moxi White"));
        shoeModelList.add(new ShoeModel("Nadia Black"));
        shoeModelList.add(new ShoeModel("Nadia Nude"));
        shoeModelList.add(new ShoeModel("Nadia White"));
        shoeModelList.add(new ShoeModel("Nataki Biscotti"));
        shoeModelList.add(new ShoeModel("Nataki LeBlanc"));
        shoeModelList.add(new ShoeModel("Nataki Toscana"));
        shoeModelList.add(new ShoeModel("Natali Creme"));
        shoeModelList.add(new ShoeModel("Natali Fleur"));
        shoeModelList.add(new ShoeModel("Natali Mist"));
        shoeModelList.add(new ShoeModel("Natali Naturale"));
        shoeModelList.add(new ShoeModel("Nava Noir"));
        shoeModelList.add(new ShoeModel("Nava Paradizo"));
        shoeModelList.add(new ShoeModel("Nayale LeBlanc"));
        shoeModelList.add(new ShoeModel("Nayale Noir"));
        shoeModelList.add(new ShoeModel("Nayale Sedona"));
        shoeModelList.add(new ShoeModel("Nayeli LeBlanc"));
        shoeModelList.add(new ShoeModel("Nayeli Naturale"));
        shoeModelList.add(new ShoeModel("Nayeli Noir"));
        shoeModelList.add(new ShoeModel("Nevara Biscotti"));
        shoeModelList.add(new ShoeModel("Nevara Fleur"));
        shoeModelList.add(new ShoeModel("Nevara LeBlanc"));
        shoeModelList.add(new ShoeModel("Nevara Sedona"));
        shoeModelList.add(new ShoeModel("Niara Biscotti"));
        shoeModelList.add(new ShoeModel("Niara LeBlanc"));
        shoeModelList.add(new ShoeModel("Niara Naturale"));
        shoeModelList.add(new ShoeModel("Niara Noir"));
        shoeModelList.add(new ShoeModel("Nishka Fleur"));
        shoeModelList.add(new ShoeModel("Nishka LeBlanc"));
        shoeModelList.add(new ShoeModel("Nishka Naturale"));
        shoeModelList.add(new ShoeModel("Noemi Black"));
        shoeModelList.add(new ShoeModel("Noemi Nude"));
        shoeModelList.add(new ShoeModel("Noemi Old Rose"));
        shoeModelList.add(new ShoeModel("Noemi Tan"));
        shoeModelList.add(new ShoeModel("Pacey Black"));
        shoeModelList.add(new ShoeModel("Pacey Nude"));
        shoeModelList.add(new ShoeModel("Pacey White"));
        shoeModelList.add(new ShoeModel("Parnika LeBlanc"));
        shoeModelList.add(new ShoeModel("Parnika Naturale"));
        shoeModelList.add(new ShoeModel("Pasqua Chamois"));
        shoeModelList.add(new ShoeModel("Pasqua LeBlanc"));
        shoeModelList.add(new ShoeModel("Pasqua Noir"));
        shoeModelList.add(new ShoeModel("Pazia Black"));
        shoeModelList.add(new ShoeModel("Pazia Nude"));
        shoeModelList.add(new ShoeModel("Pazia Ricotta"));
        shoeModelList.add(new ShoeModel("Pazia White"));
        shoeModelList.add(new ShoeModel("Pixi ApricotBeige"));
        shoeModelList.add(new ShoeModel("Pixi Biscotti"));
        shoeModelList.add(new ShoeModel("Pixi Black"));
        shoeModelList.add(new ShoeModel("Pixi White"));
        shoeModelList.add(new ShoeModel("Pola Biscotti"));
        shoeModelList.add(new ShoeModel("Pola Black"));
        shoeModelList.add(new ShoeModel("Pola Nude"));
        shoeModelList.add(new ShoeModel("Pola White"));
        shoeModelList.add(new ShoeModel("Portia Ricotta"));
        shoeModelList.add(new ShoeModel("Priya Biscotti"));
        shoeModelList.add(new ShoeModel("Priya Black"));
        shoeModelList.add(new ShoeModel("Priya Nude"));
        shoeModelList.add(new ShoeModel("Priya White"));
        shoeModelList.add(new ShoeModel("Ranais LeBlanc"));
        shoeModelList.add(new ShoeModel("Ranais Naturale"));
        shoeModelList.add(new ShoeModel("Ranais Toscana"));
        shoeModelList.add(new ShoeModel("Rio White"));
        shoeModelList.add(new ShoeModel("Rori Alabaster"));
        shoeModelList.add(new ShoeModel("Rori Biscotti"));
        shoeModelList.add(new ShoeModel("Rori Calico"));
        shoeModelList.add(new ShoeModel("Rori Chamois"));
        shoeModelList.add(new ShoeModel("Rori Creme"));
        shoeModelList.add(new ShoeModel("Rori Denim"));
        shoeModelList.add(new ShoeModel("Rori Dimity"));
        shoeModelList.add(new ShoeModel("Rori LeBlanc"));
        shoeModelList.add(new ShoeModel("Rori LimitedColorplay"));
        shoeModelList.add(new ShoeModel("Rori Naturale"));
        shoeModelList.add(new ShoeModel("Rori Navajo"));
        shoeModelList.add(new ShoeModel("Rori Noir"));
        shoeModelList.add(new ShoeModel("Rori Toscana"));
        shoeModelList.add(new ShoeModel("Rory Creme"));
        shoeModelList.add(new ShoeModel("Rory Fleur"));
        shoeModelList.add(new ShoeModel("Rory Dimity"));
        shoeModelList.add(new ShoeModel("Rory Toscana"));
        shoeModelList.add(new ShoeModel("Roscoe LeBlanc"));
        shoeModelList.add(new ShoeModel("Roscoe Naturale"));
        shoeModelList.add(new ShoeModel("Roscoe Noir"));
        shoeModelList.add(new ShoeModel("Roux Noir"));
        shoeModelList.add(new ShoeModel("Shania Biscotti"));
        shoeModelList.add(new ShoeModel("Shania Cashew"));
        shoeModelList.add(new ShoeModel("Shania Nude"));
        shoeModelList.add(new ShoeModel("Shania White"));
        shoeModelList.add(new ShoeModel("Shifra Biscotti"));
        shoeModelList.add(new ShoeModel("Shifra Fleur"));
        shoeModelList.add(new ShoeModel("Shifra LeBlanc"));
        shoeModelList.add(new ShoeModel("Shifra Noir"));
        shoeModelList.add(new ShoeModel("Shique Beige"));
        shoeModelList.add(new ShoeModel("Shiva Biscotti"));
        shoeModelList.add(new ShoeModel("Shiva Nude"));
        shoeModelList.add(new ShoeModel("Shiva White"));
        shoeModelList.add(new ShoeModel("Shreya Aqua"));
        shoeModelList.add(new ShoeModel("Shreya Baked"));
        shoeModelList.add(new ShoeModel("Shreya Biscotti"));
        shoeModelList.add(new ShoeModel("Shreya Black"));
        shoeModelList.add(new ShoeModel("Shreya Creme"));
        shoeModelList.add(new ShoeModel("Shreya Ecru"));
        shoeModelList.add(new ShoeModel("Shreya Grape"));
        shoeModelList.add(new ShoeModel("Shreya Lime"));
        shoeModelList.add(new ShoeModel("Shreya Macadamia"));
        shoeModelList.add(new ShoeModel("Shreya Nude"));
        shoeModelList.add(new ShoeModel("Shreya Oat"));
        shoeModelList.add(new ShoeModel("Shreya Rosette"));
        shoeModelList.add(new ShoeModel("Shreya Terracotta"));
        shoeModelList.add(new ShoeModel("Shreya Toffee"));
        shoeModelList.add(new ShoeModel("Shreya Turtledove"));
        shoeModelList.add(new ShoeModel("Shreya Whip"));
        shoeModelList.add(new ShoeModel("Shreya White"));
        shoeModelList.add(new ShoeModel("Sienna Baked"));
        shoeModelList.add(new ShoeModel("Sienna Turtledove"));
        shoeModelList.add(new ShoeModel("Iqra Paradizo"));
        shoeModelList.add(new ShoeModel("Iqra Rojo"));
        shoeModelList.add(new ShoeModel("Eara Verde"));
        shoeModelList.add(new ShoeModel("Sydney Biscotti"));
        shoeModelList.add(new ShoeModel("Sydney Cashew"));
        shoeModelList.add(new ShoeModel("Sydney Sierra"));
        shoeModelList.add(new ShoeModel("Sydney Tangerine"));
        shoeModelList.add(new ShoeModel("Sydney White"));

    }

    public void displayRV(){
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(linearLayoutManager);
        setAdapter();
    }

    public void setAdapter(){
        shoeAdapter = new ShoeAdapter(shoeModelList, this, this::selectedShoe);
        recyclerView.setAdapter(shoeAdapter);
    }

    @Override
    public void selectedShoe(ShoeModel shoeModel) {
//        Toast.makeText(this, "Selected shoe " + shoeModel.getName(), Toast.LENGTH_SHORT).show();
        startActivity(new Intent(this, SelectedShoe.class).putExtra("data", shoeModel));
    }
}