package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageView;
import android.widget.PopupMenu;
import android.widget.SearchView;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;

import java.util.ArrayList;
import java.util.List;

public class Inventory extends AppCompatActivity implements ShoeAdapter.ShoeClickListener{

    SearchView searchView;
    RecyclerView recyclerView;
    ShoeAdapter shoeAdapter;
    List<ShoeModel> shoeModelList = new ArrayList<>();

    ImageView backBtn, menupopbtn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_inventory);

        searchView = findViewById(R.id.searchView);
        recyclerView = findViewById(R.id.recyclerView);

        backBtn = findViewById(R.id.backBtn);
        backBtn.setOnClickListener(view -> startActivity(new Intent(getApplicationContext(), MainActivity.class)));

        menupopbtn = findViewById(R.id.menupopbtn);
        menupopbtn.setOnClickListener(view -> {
            PopupMenu popupMenu = new PopupMenu(getApplicationContext(), menupopbtn);
            popupMenu.getMenuInflater().inflate(R.menu.option_menu, popupMenu.getMenu());

            popupMenu.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener() {
                @Override
                public boolean onMenuItemClick(MenuItem menuItem) {
                    switch (menuItem.getItemId()) {

                        case R.id.resetUserPassword:
                            startActivity(new Intent(getApplicationContext(), Resetpassword.class));
                            return true;

                        case R.id.logoutbtn:
                            FirebaseAuth.getInstance().signOut();
                            startActivity(new Intent(getApplicationContext(), LoginActivity.class));
                            finish();
                            return true;
                    }
                    return false;
                }
            });
            popupMenu.show();
        });

        displaySearch();
        setData();
        displayRV();

    }

    // filtered list for searchView
    private void displaySearch() {
        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                List<ShoeModel> filteredList = new ArrayList<>();
                for (ShoeModel item: shoeModelList){
                    if (item.getName().toLowerCase().contains(newText.toLowerCase())){
                        filteredList.add(item);
                    }
                    shoeAdapter.filterList(filteredList);
                }
                return true;
            }
        });
    }

    // data for shoe names
    public void setData() {

        shoeModelList.add(new ShoeModel("Akalia White", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Black", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Bleu", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Blush", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Daffodil", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Golden", null, null, null));
        shoeModelList.add(new ShoeModel("Ada Periwinkle", null, null, null));
        shoeModelList.add(new ShoeModel("Ada White", null, null, null));
        shoeModelList.add(new ShoeModel("Adria Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Adria Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Adria Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Akalia Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Alaia Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Alaia Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Alaia Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Alaia Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Alana Black", null, null, null));
        shoeModelList.add(new ShoeModel("Alana Bleu", null, null, null));
        shoeModelList.add(new ShoeModel("Alana Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Alana Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Alana White", null, null, null));
        shoeModelList.add(new ShoeModel("Alcott Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Alcott Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Alcott Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Alcott White", null, null, null));
        shoeModelList.add(new ShoeModel("Alva Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Alva Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Alva Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Amara Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Amara Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Amara Orchid", null, null, null));
        shoeModelList.add(new ShoeModel("Amara White", null, null, null));
        shoeModelList.add(new ShoeModel("Amber Black", null, null, null));
        shoeModelList.add(new ShoeModel("Amber Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Amber Daffodil", null, null, null));
        shoeModelList.add(new ShoeModel("Amber Lilac", null, null, null));
        shoeModelList.add(new ShoeModel("Amber Oat", null, null, null));
        shoeModelList.add(new ShoeModel("Amber White", null, null, null));
        shoeModelList.add(new ShoeModel("Analia Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Analia Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Ashanti Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Ashanti Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Ashanti White", null, null, null));
        shoeModelList.add(new ShoeModel("Aztrid Black", null, null, null));
        shoeModelList.add(new ShoeModel("Aztrid Cloud", null, null, null));
        shoeModelList.add(new ShoeModel("Aztrid Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Bahari Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Bahari Ecru", null, null, null));
        shoeModelList.add(new ShoeModel("Bahari Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Becca Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Becca Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Becca White", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza Lime", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza Old Rose", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza Sierra", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza Tangerine 1", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza Tricolor", null, null, null));
        shoeModelList.add(new ShoeModel("Beyza White", null, null, null));
        shoeModelList.add(new ShoeModel("Binx Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Binx Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Binx Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Blair Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Blair Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Blair White", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Black", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Cloud", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Honey", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Rosette", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Tofu", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Tortoise", null, null, null));
        shoeModelList.add(new ShoeModel("Blanche Turtledove", null, null, null));
        shoeModelList.add(new ShoeModel("Blythe Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Blythe Black", null, null, null));
        shoeModelList.add(new ShoeModel("Blythe Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Blythe White", null, null, null));
        shoeModelList.add(new ShoeModel("Brea Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Brea White", null, null, null));
        shoeModelList.add(new ShoeModel("Brita Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Brita Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Brita White", null, null, null));
        shoeModelList.add(new ShoeModel("Briza Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Briza Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Briza Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Calais Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Calais Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Cali Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Cali Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Cali Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Cali Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Calista Black", null, null, null));
        shoeModelList.add(new ShoeModel("Calista Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Calista Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Calista White", null, null, null));
        shoeModelList.add(new ShoeModel("Calla Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Calla White", null, null, null));
        shoeModelList.add(new ShoeModel("Candice Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Candice Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Candice Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Caprice Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Caprice Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Caprice Toast", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Beige", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Black Leather", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Black Suede", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Blanc Gray", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Mauve", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Milk", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Nude Leather", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Nude Suede", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Tan", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Toffee", null, null, null));
        shoeModelList.add(new ShoeModel("Cari Wine Red", null, null, null));
        shoeModelList.add(new ShoeModel("Carin Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Carin Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Carin Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Carin Naturale Old", null, null, null));
        shoeModelList.add(new ShoeModel("Carin Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Carin Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Casia Bleu", null, null, null));
        shoeModelList.add(new ShoeModel("Casia Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Casia Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Casia White", null, null, null));
        shoeModelList.add(new ShoeModel("Caya Black", null, null, null));
        shoeModelList.add(new ShoeModel("Caya Bone", null, null, null));
        shoeModelList.add(new ShoeModel("Caya Tortoise", null, null, null));
        shoeModelList.add(new ShoeModel("Caya White", null, null, null));
        shoeModelList.add(new ShoeModel("Celeste Black", null, null, null));
        shoeModelList.add(new ShoeModel("Celeste Cloud", null, null, null));
        shoeModelList.add(new ShoeModel("Celeste Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Chantal White", null, null, null));
        shoeModelList.add(new ShoeModel("Charlotte Black", null, null, null));
        shoeModelList.add(new ShoeModel("Charlotte Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Charlotte Nude Leather", null, null, null));
        shoeModelList.add(new ShoeModel("Charlotte White", null, null, null));
        shoeModelList.add(new ShoeModel("Ciera Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Cinzia Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Cinzia Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Cinzia Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Cinzia Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Cirila Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Cirila Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Citla Claro", null, null, null));
        shoeModelList.add(new ShoeModel("Citla Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Citla Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Citla Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Clea Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Clea Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Cleo Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Cleo Black", null, null, null));
        shoeModelList.add(new ShoeModel("Cleo Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Cleo Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Cora Black Suede", null, null, null));
        shoeModelList.add(new ShoeModel("Cora Nude Suede", null, null, null));
        shoeModelList.add(new ShoeModel("Cora Tan Suede", null, null, null));
        shoeModelList.add(new ShoeModel("Corin Black", null, null, null));
        shoeModelList.add(new ShoeModel("Corin Blanc Gray", null, null, null));
        shoeModelList.add(new ShoeModel("Corin Mauve", null, null, null));
        shoeModelList.add(new ShoeModel("Corin Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Corin Old Rose", null, null, null));
        shoeModelList.add(new ShoeModel("Corin Tan", null, null, null));
        shoeModelList.add(new ShoeModel("Corin White", null, null, null));
        shoeModelList.add(new ShoeModel("Dakari Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Dakari Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Dakari Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Dakari Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Damari Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Damari Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Damari Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Damia Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Damia Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Damia Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Dania Ochre", null, null, null));
        shoeModelList.add(new ShoeModel("Dania Old Rose", null, null, null));
        shoeModelList.add(new ShoeModel("Dania White", null, null, null));
        shoeModelList.add(new ShoeModel("Darika Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Darika Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Darika Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Darika Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Darinka Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Darinka Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Darinka Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Darya Citron", null, null, null));
        shoeModelList.add(new ShoeModel("Darya Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Darya White", null, null, null));
        shoeModelList.add(new ShoeModel("Davina Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Davina Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Dawn Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Dawn Black", null, null, null));
        shoeModelList.add(new ShoeModel("Dawn Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Dawn Honey", null, null, null));
        shoeModelList.add(new ShoeModel("Dawn Tortoise", null, null, null));
        shoeModelList.add(new ShoeModel("Dawn White", null, null, null));
        shoeModelList.add(new ShoeModel("Dayra Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Dayra Pecan", null, null, null));
        shoeModelList.add(new ShoeModel("Dayra White", null, null, null));
        shoeModelList.add(new ShoeModel("Dazia Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Dazia Toast", null, null, null));
        shoeModelList.add(new ShoeModel("Dazia White", null, null, null));
        shoeModelList.add(new ShoeModel("Deja Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Deja Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Deja Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Devi Bisque", null, null, null));
        shoeModelList.add(new ShoeModel("Devi Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Devi Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Devi Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Devi Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Devi Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Dimitra Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Dimitra Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Divya Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Divya Black", null, null, null));
        shoeModelList.add(new ShoeModel("Divya Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Divya Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Dorca Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Dorca Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Dorca Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Dreya Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Dreya Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Dreya Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Dreya Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Dyani Chamois", null, null, null));
        shoeModelList.add(new ShoeModel("Dyani Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Dyani Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Eara Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Eara Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Efia Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Efia Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Efia Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Efia Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Eira Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Eira Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Eira Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Eira Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Elakshi Sandstone", null, null, null));
        shoeModelList.add(new ShoeModel("Elakshi Sierra", null, null, null));
        shoeModelList.add(new ShoeModel("Elakshi White", null, null, null));
        shoeModelList.add(new ShoeModel("Elayna Amber", null, null, null));
        shoeModelList.add(new ShoeModel("Elayna Aqua", null, null, null));
        shoeModelList.add(new ShoeModel("Elayna Citron", null, null, null));
        shoeModelList.add(new ShoeModel("Elayna White", null, null, null));
        shoeModelList.add(new ShoeModel("Eliri Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Eliri Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Eliri Ecru", null, null, null));
        shoeModelList.add(new ShoeModel("Eliri White", null, null, null));
        shoeModelList.add(new ShoeModel("Elva Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Elva Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Elva Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Emari Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Emari Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Emari Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Emeli Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Emeli Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Emeli Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Enari Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Enari Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Enari Rojo", null, null, null));
        shoeModelList.add(new ShoeModel("Ercila Bleu", null, null, null));
        shoeModelList.add(new ShoeModel("Ercila Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Ercila Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Erma Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Erma Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Erma White", null, null, null));
        shoeModelList.add(new ShoeModel("Eshika Calico", null, null, null));
        shoeModelList.add(new ShoeModel("Eshika Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Eshika Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Eula Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Eula Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Eula Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Ezra Black", null, null, null));
        shoeModelList.add(new ShoeModel("Ezra Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Ezra Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Ezra Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Ezra White", null, null, null));
        shoeModelList.add(new ShoeModel("Faiqa Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Faiqa Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Faiqa Majolica", null, null, null));
        shoeModelList.add(new ShoeModel("Faiqa Mist", null, null, null));
        shoeModelList.add(new ShoeModel("Faiza Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Faiza Cappuccino", null, null, null));
        shoeModelList.add(new ShoeModel("Faiza White", null, null, null));
        shoeModelList.add(new ShoeModel("Farida Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Farida Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Fatou Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Fatou Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Fatou Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Fatou Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Fiza Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Fiza Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Florentine Bisque", null, null, null));
        shoeModelList.add(new ShoeModel("Florentine Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Fraya Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Fraya Le Blanc 1", null, null, null));
        shoeModelList.add(new ShoeModel("Fraya Naturale 1", null, null, null));
        shoeModelList.add(new ShoeModel("Freda Black", null, null, null));
        shoeModelList.add(new ShoeModel("Freda Bleu", null, null, null));
        shoeModelList.add(new ShoeModel("Freda Daffodil", null, null, null));
        shoeModelList.add(new ShoeModel("Freda White", null, null, null));
        shoeModelList.add(new ShoeModel("Fritz Bleu", null, null, null));
        shoeModelList.add(new ShoeModel("Fritz Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Fritz Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Gada Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Gada Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Gada Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Gajra Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Gajra Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Gajra Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Galea Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Galea Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Galea White", null, null, null));
        shoeModelList.add(new ShoeModel("Gali Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Gali Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Gali Oceane", null, null, null));
        shoeModelList.add(new ShoeModel("Galia Blue Mist", null, null, null));
        shoeModelList.add(new ShoeModel("Galia Periwinkle", null, null, null));
        shoeModelList.add(new ShoeModel("Galia White", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri Black", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri Caramel", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri Lilac", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri Rosewater", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri Tangerine", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri White", null, null, null));
        shoeModelList.add(new ShoeModel("Gauri Wine Red", null, null, null));
        shoeModelList.add(new ShoeModel("Gayatri Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Gayatri Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Gayatri Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Georgina Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Gerta Mist", null, null, null));
        shoeModelList.add(new ShoeModel("Gerta Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Gerta Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Gerta White", null, null, null));
        shoeModelList.add(new ShoeModel("Giada Black", null, null, null));
        shoeModelList.add(new ShoeModel("Giada Rosette", null, null, null));
        shoeModelList.add(new ShoeModel("Giada Toast", null, null, null));
        shoeModelList.add(new ShoeModel("Giada White", null, null, null));
        shoeModelList.add(new ShoeModel("Giavanna Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Giavanna Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Giavanna Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Gita Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Gita Black", null, null, null));
        shoeModelList.add(new ShoeModel("Gita Natuarale", null, null, null));
        shoeModelList.add(new ShoeModel("Gita Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Hada Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Hada Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Hada Mauve", null, null, null));
        shoeModelList.add(new ShoeModel("Hada Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Hada White", null, null, null));
        shoeModelList.add(new ShoeModel("Hadiya Aqua", null, null, null));
        shoeModelList.add(new ShoeModel("Hadiya Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Hadiya Orchid", null, null, null));
        shoeModelList.add(new ShoeModel("Hadiya White", null, null, null));
        shoeModelList.add(new ShoeModel("Hailey Black", null, null, null));
        shoeModelList.add(new ShoeModel("Hailey Caramel", null, null, null));
        shoeModelList.add(new ShoeModel("Hailey Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Hailey White", null, null, null));
        shoeModelList.add(new ShoeModel("Haira Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Haira Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Hajra Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Hajra Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Hajra Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Hajra Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Hajra Revera", null, null, null));
        shoeModelList.add(new ShoeModel("Hajra Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Canta", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Dyad", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Palmera", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Rayo", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Rosa", null, null, null));
        shoeModelList.add(new ShoeModel("Haldis Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Halia Celadon", null, null, null));
        shoeModelList.add(new ShoeModel("Halia Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Halia Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Hania Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Hania Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Hania White", null, null, null));
        shoeModelList.add(new ShoeModel("Haniya Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Haniya Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Haniya Woven", null, null, null));
        shoeModelList.add(new ShoeModel("Hanvika Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Hanvika Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Hara Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Hara Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Hara Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Harini Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Harini Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Harini Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Harri Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Harri Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Havika Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Havika Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Havika Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Haya Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Haya Black", null, null, null));
        shoeModelList.add(new ShoeModel("Haya Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Haya Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Haya White", null, null, null));
        shoeModelList.add(new ShoeModel("Henika Chamois", null, null, null));
        shoeModelList.add(new ShoeModel("Henika Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Huda Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Huda Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Huda White", null, null, null));
        shoeModelList.add(new ShoeModel("Ida Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Ida Black", null, null, null));
        shoeModelList.add(new ShoeModel("Ida White", null, null, null));
        shoeModelList.add(new ShoeModel("Iman Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Iman Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Iman Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Inez Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Inez Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Inez Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Ingrid White", null, null, null));
        shoeModelList.add(new ShoeModel("Iqra Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Jaca Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Jaca Fleur 1", null, null, null));
        shoeModelList.add(new ShoeModel("Jaca Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Jaca Le Blanc 1", null, null, null));
        shoeModelList.add(new ShoeModel("Jaca Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Jaca Naturale 1", null, null, null));
        shoeModelList.add(new ShoeModel("Jaca Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Jaci Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Jada Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Jada Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Jada Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Jada Revera", null, null, null));
        shoeModelList.add(new ShoeModel("Jada Rocio", null, null, null));
        shoeModelList.add(new ShoeModel("Jaliya Black 1", null, null, null));
        shoeModelList.add(new ShoeModel("Jaliya Calke Green", null, null, null));
        shoeModelList.add(new ShoeModel("Jaliya Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Jaliya White", null, null, null));
        shoeModelList.add(new ShoeModel("Janeva Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Janeva Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Janeva Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Janeva Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Jaria Chamois", null, null, null));
        shoeModelList.add(new ShoeModel("Jaria Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Jemimah Black", null, null, null));
        shoeModelList.add(new ShoeModel("Jemimah Gray", null, null, null));
        shoeModelList.add(new ShoeModel("Jemimah Light Blue", null, null, null));
        shoeModelList.add(new ShoeModel("Jemimah Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Jemimah White", null, null, null));
        shoeModelList.add(new ShoeModel("Joia Brassica", null, null, null));
        shoeModelList.add(new ShoeModel("Joia Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Jovana Biscotti Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Jovana Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Jovana Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Jovana Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Kadija Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kadija Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Kadija Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Kadija Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Kaia Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kaia Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Kaia Majolica", null, null, null));
        shoeModelList.add(new ShoeModel("Kaia Mist", null, null, null));
        shoeModelList.add(new ShoeModel("Kaia Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Kaia Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Kaia White", null, null, null));
        shoeModelList.add(new ShoeModel("Kaija Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kaija Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Kaira Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Kaira Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Kaira White", null, null, null));
        shoeModelList.add(new ShoeModel("Kala Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kala Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Kala White", null, null, null));
        shoeModelList.add(new ShoeModel("Kalani Dimity", null, null, null));
        shoeModelList.add(new ShoeModel("Kalani Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kalani Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Kali Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Kali White", null, null, null));
        shoeModelList.add(new ShoeModel("Kamala Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kamala Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Kamala Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kanika Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kanika Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Kanika Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Kaori Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kaori Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Kaori White", null, null, null));
        shoeModelList.add(new ShoeModel("Kashvi Black", null, null, null));
        shoeModelList.add(new ShoeModel("Kashvi Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Kashvi White", null, null, null));
        shoeModelList.add(new ShoeModel("Kashvi Wine Red", null, null, null));
        shoeModelList.add(new ShoeModel("Katara Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Katara Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kerala Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kerala Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kerala Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Kerala Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Keva Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Keva Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Keva Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Keva Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Kiari Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Kiari Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Kiari Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Kimaya Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kimaya Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Kimaya Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Kimika Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kimika Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Kimika Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Kriva Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Kriva Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Kriva Paradizo", null, null, null));
        shoeModelList.add(new ShoeModel("Kriva Rojo", null, null, null));
        shoeModelList.add(new ShoeModel("Kyla Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Lacara Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Lacara Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Lacara Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Latara Chamois", null, null, null));
        shoeModelList.add(new ShoeModel("Latara Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Latara Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Layan Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Layan Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Layan Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Layla Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Layla Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Layla White", null, null, null));
        shoeModelList.add(new ShoeModel("Leana Dawn", null, null, null));
        shoeModelList.add(new ShoeModel("Leana Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Leana Sage Green", null, null, null));
        shoeModelList.add(new ShoeModel("Leana Tortoise", null, null, null));
        shoeModelList.add(new ShoeModel("Leana White", null, null, null));
        shoeModelList.add(new ShoeModel("Litzy Bicotti", null, null, null));
        shoeModelList.add(new ShoeModel("Litzy Bleu", null, null, null));
        shoeModelList.add(new ShoeModel("Litzy Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Litzy Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Litzy Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Londyn Blanc Gray", null, null, null));
        shoeModelList.add(new ShoeModel("Londyn White", null, null, null));
        shoeModelList.add(new ShoeModel("Lora Black 1", null, null, null));
        shoeModelList.add(new ShoeModel("Lora Nude 1", null, null, null));
        shoeModelList.add(new ShoeModel("Lora White", null, null, null));
        shoeModelList.add(new ShoeModel("Lorelei Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Lorelei Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Lorelei Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Loretta Beige", null, null, null));
        shoeModelList.add(new ShoeModel("Loretta Black", null, null, null));
        shoeModelList.add(new ShoeModel("Loretta Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Loretta White", null, null, null));
        shoeModelList.add(new ShoeModel("Lori Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Lori Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Lori Palomino", null, null, null));
        shoeModelList.add(new ShoeModel("Lori White", null, null, null));
        shoeModelList.add(new ShoeModel("Luxi Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Luxi Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Luxi Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Luxi Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Macara Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Macara Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Macara Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Macara Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Maija Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Maija Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Maija Revera", null, null, null));
        shoeModelList.add(new ShoeModel("Malia Black", null, null, null));
        shoeModelList.add(new ShoeModel("Malia Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Malia Tortoise", null, null, null));
        shoeModelList.add(new ShoeModel("Malia White", null, null, null));
        shoeModelList.add(new ShoeModel("Malka Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Malka Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Malka Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Malka Rosa", null, null, null));
        shoeModelList.add(new ShoeModel("Malka Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Marica Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Marica Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Marica Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Marica Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Marie Black", null, null, null));
        shoeModelList.add(new ShoeModel("Marie Blush", null, null, null));
        shoeModelList.add(new ShoeModel("Marie Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Marie Periwinkle", null, null, null));
        shoeModelList.add(new ShoeModel("Marie Taupe", null, null, null));
        shoeModelList.add(new ShoeModel("Marie White", null, null, null));
        shoeModelList.add(new ShoeModel("Marie Wine Red", null, null, null));
        shoeModelList.add(new ShoeModel("Marzia Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Marzia Claro", null, null, null));
        shoeModelList.add(new ShoeModel("Marzia Ecru", null, null, null));
        shoeModelList.add(new ShoeModel("Marzia White", null, null, null));
        shoeModelList.add(new ShoeModel("Meera Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Meera Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Meera White", null, null, null));
        shoeModelList.add(new ShoeModel("Melina Toast", null, null, null));
        shoeModelList.add(new ShoeModel("Melina Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Melina White", null, null, null));
        shoeModelList.add(new ShoeModel("Meya Black", null, null, null));
        shoeModelList.add(new ShoeModel("Meya Cappuccino", null, null, null));
        shoeModelList.add(new ShoeModel("Meya Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Meya Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Meya White", null, null, null));
        shoeModelList.add(new ShoeModel("Mireya Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Mireya Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Mireya White", null, null, null));
        shoeModelList.add(new ShoeModel("Mohini Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Mohini White", null, null, null));
        shoeModelList.add(new ShoeModel("Moxi", null, null, null));
        shoeModelList.add(new ShoeModel("Moxi Daffodil", null, null, null));
        shoeModelList.add(new ShoeModel("Moxi Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Moxi White", null, null, null));
        shoeModelList.add(new ShoeModel("Nadia Black", null, null, null));
        shoeModelList.add(new ShoeModel("Nadia Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Nadia White", null, null, null));
        shoeModelList.add(new ShoeModel("Nataki Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Nataki Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Nataki Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Natali Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Natali Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Natali Mist", null, null, null));
        shoeModelList.add(new ShoeModel("Natali Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Nava Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Nava Paradizo", null, null, null));
        shoeModelList.add(new ShoeModel("Nayale Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Nayale Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Nayale Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Nayeli Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Nayeli Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Nayeli Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Nevara Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Nevara Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Nevara Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Nevara Sedona", null, null, null));
        shoeModelList.add(new ShoeModel("Niara Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Niara Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Niara Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Niara Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Nishka Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Nishka Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Nishka Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Noemi Black", null, null, null));
        shoeModelList.add(new ShoeModel("Noemi Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Noemi Old Rose", null, null, null));
        shoeModelList.add(new ShoeModel("Noemi Tan", null, null, null));
        shoeModelList.add(new ShoeModel("Pacey Black", null, null, null));
        shoeModelList.add(new ShoeModel("Pacey Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Pacey White", null, null, null));
        shoeModelList.add(new ShoeModel("Parnika Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Parnika Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Pasqua Chamois", null, null, null));
        shoeModelList.add(new ShoeModel("Pasqua Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Pasqua Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Pazia Black", null, null, null));
        shoeModelList.add(new ShoeModel("Pazia Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Pazia Ricotta", null, null, null));
        shoeModelList.add(new ShoeModel("Pazia White", null, null, null));
        shoeModelList.add(new ShoeModel("Pixi Apricot Beige", null, null, null));
        shoeModelList.add(new ShoeModel("Pixi Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Pixi Black", null, null, null));
        shoeModelList.add(new ShoeModel("Pixi White", null, null, null));
        shoeModelList.add(new ShoeModel("Pola Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Pola Black", null, null, null));
        shoeModelList.add(new ShoeModel("Pola Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Pola White", null, null, null));
        shoeModelList.add(new ShoeModel("Portia Ricotta", null, null, null));
        shoeModelList.add(new ShoeModel("Priya Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Priya Black", null, null, null));
        shoeModelList.add(new ShoeModel("Priya Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Priya White", null, null, null));
        shoeModelList.add(new ShoeModel("Ranais Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Ranais Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Ranais Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Rio White", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Alabaster", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Calico", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Chamois", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Denim", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Dimity", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Limited Colorplay", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Navajo", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Rori Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Rory Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Rory Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Rory Dimity", null, null, null));
        shoeModelList.add(new ShoeModel("Rory Toscana", null, null, null));
        shoeModelList.add(new ShoeModel("Roscoe Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Roscoe Naturale", null, null, null));
        shoeModelList.add(new ShoeModel("Roscoe Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Roux Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Shania Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Shania Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Shania Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Shania White", null, null, null));
        shoeModelList.add(new ShoeModel("Shifra Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Shifra Fleur", null, null, null));
        shoeModelList.add(new ShoeModel("Shifra Le Blanc", null, null, null));
        shoeModelList.add(new ShoeModel("Shifra Noir", null, null, null));
        shoeModelList.add(new ShoeModel("Shique Beige", null, null, null));
        shoeModelList.add(new ShoeModel("Shiva Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Shiva Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Shiva White", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Aqua", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Baked", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Black", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Creme", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Ecru", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Grape", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Lime", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Macadamia", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Nude", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Oat", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Rosette", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Terracotta", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Toffee", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Turtledove", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya Whip", null, null, null));
        shoeModelList.add(new ShoeModel("Shreya White", null, null, null));
        shoeModelList.add(new ShoeModel("Sienna Baked", null, null, null));
        shoeModelList.add(new ShoeModel("Sienna Turtledove", null, null, null));
        shoeModelList.add(new ShoeModel("Iqra Paradizo", null, null, null));
        shoeModelList.add(new ShoeModel("Iqra Rojo", null, null, null));
        shoeModelList.add(new ShoeModel("Eara Verde", null, null, null));
        shoeModelList.add(new ShoeModel("Sydney Biscotti", null, null, null));
        shoeModelList.add(new ShoeModel("Sydney Cashew", null, null, null));
        shoeModelList.add(new ShoeModel("Sydney Sierra", null, null, null));
        shoeModelList.add(new ShoeModel("Sydney Tangerine", null, null, null));
        shoeModelList.add(new ShoeModel("Sydney White", null, null, null));

    }

    public void displayRV(){
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(linearLayoutManager);
        setAdapter();
    }

    public void setAdapter(){
        shoeAdapter = new ShoeAdapter(shoeModelList, this, this::selectedShoe);
        recyclerView.setAdapter(shoeAdapter);
    }

    @Override
    public void selectedShoe(ShoeModel shoeModel) {
//        Toast.makeText(this, "Selected shoe " + shoeModel.getName(), Toast.LENGTH_SHORT).show();
        startActivity(new Intent(this, SelectedShoe.class).putExtra("data", shoeModel));
    }
}